// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEShbYJUDXaLov6rSOtJLaVPTcf8PrH34',
    appId: '1:206034680472:web:PLACEHOLDER',
    messagingSenderId: '206034680472',
    projectId: 'yourspace-regional-68049',
    authDomain: 'yourspace-regional-68049.firebaseapp.com',
    storageBucket: 'yourspace-regional-68049.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEShbYJUDXaLov6rSOtJLaVPTcf8PrH34',
    appId: '1:206034680472:android:caeaf951a08ba488552eed',
    messagingSenderId: '206034680472',
    projectId: 'yourspace-regional-68049',
    storageBucket: 'yourspace-regional-68049.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEShbYJUDXaLov6rSOtJLaVPTcf8PrH34',
    appId: '1:206034680472:ios:PLACEHOLDER552eed',
    messagingSenderId: '206034680472',
    projectId: 'yourspace-regional-68049',
    storageBucket: 'yourspace-regional-68049.firebasestorage.app',
    iosBundleId: 'com.duodo.partner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEShbYJUDXaLov6rSOtJLaVPTcf8PrH34',
    appId: '1:206034680472:ios:PLACEHOLDER552eed',
    messagingSenderId: '206034680472',
    projectId: 'yourspace-regional-68049',
    storageBucket: 'yourspace-regional-68049.firebasestorage.app',
    iosBundleId: 'com.duodo.partner',
  );
}
